// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhrasalVerbs.Application.Database;

#nullable disable

namespace PhrasalVerbs.Application.Database.Migrations
{
    [DbContext(typeof(PhrasalVerbsContext))]
    [Migration("20250303085737_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PhrasalVerbs.Application.Models.PhrasalVerb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Verb")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PhrasalVerbs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Verb = "Abide by"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Verb = "Account for"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Verb = "Ache for"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            Verb = "Act on"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            Verb = "Act out"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            Verb = "Act up"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            Verb = "Act upon"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            Verb = "Add on"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            Verb = "Add up"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-00000000000a"),
                            Verb = "Add up to"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-00000000000b"),
                            Verb = "Advise against"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-00000000000c"),
                            Verb = "Agree with"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-00000000000d"),
                            Verb = "Aim at"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-00000000000e"),
                            Verb = "Allow for"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-00000000000f"),
                            Verb = "Angle for"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            Verb = "Answer back"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            Verb = "Answer for"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000012"),
                            Verb = "Argue down"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000013"),
                            Verb = "Argue out"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000014"),
                            Verb = "Ask about"
                        });
                });

            modelBuilder.Entity("PhrasalVerbs.Application.Models.Translation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PhrasalVerbId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Verb")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PhrasalVerbId");

                    b.ToTable("Translations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Language = "pl",
                            PhrasalVerbId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Verb = "Zaakceptować lub postępować zgodnie z decyzją lub zasadą"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Language = "pl",
                            PhrasalVerbId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Verb = "Wyjaśnić"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Language = "pl",
                            PhrasalVerbId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Verb = "Bardzo czegoś lub kogoś chcieć"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            Language = "pl",
                            PhrasalVerbId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Verb = "Podjąć działania na podstawie otrzymanych informacji"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            Language = "pl",
                            PhrasalVerbId = new Guid("00000000-0000-0000-0000-000000000005"),
                            Verb = "Odtworzyć coś za pomocą gestów"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            Language = "pl",
                            PhrasalVerbId = new Guid("00000000-0000-0000-0000-000000000006"),
                            Verb = "Zachowywać się źle lub dziwnie"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            Language = "pl",
                            PhrasalVerbId = new Guid("00000000-0000-0000-0000-000000000007"),
                            Verb = "Podjąć działania na podstawie otrzymanych informacji"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            Language = "pl",
                            PhrasalVerbId = new Guid("00000000-0000-0000-0000-000000000008"),
                            Verb = "Dodać do obliczeń"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            Language = "pl",
                            PhrasalVerbId = new Guid("00000000-0000-0000-0000-000000000009"),
                            Verb = "Dokonać matematycznego podsumowania"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-00000000000a"),
                            Language = "pl",
                            PhrasalVerbId = new Guid("00000000-0000-0000-0000-00000000000a"),
                            Verb = "Doprowadzić do"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-00000000000b"),
                            Language = "pl",
                            PhrasalVerbId = new Guid("00000000-0000-0000-0000-00000000000b"),
                            Verb = "Odradzać"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-00000000000c"),
                            Language = "pl",
                            PhrasalVerbId = new Guid("00000000-0000-0000-0000-00000000000c"),
                            Verb = "Zgadzać się z"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-00000000000d"),
                            Language = "pl",
                            PhrasalVerbId = new Guid("00000000-0000-0000-0000-00000000000d"),
                            Verb = "Celować w"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-00000000000e"),
                            Language = "pl",
                            PhrasalVerbId = new Guid("00000000-0000-0000-0000-00000000000e"),
                            Verb = "Uwzględniać"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-00000000000f"),
                            Language = "pl",
                            PhrasalVerbId = new Guid("00000000-0000-0000-0000-00000000000f"),
                            Verb = "Zabiegać o coś"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            Language = "pl",
                            PhrasalVerbId = new Guid("00000000-0000-0000-0000-000000000010"),
                            Verb = "Odpyskować"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            Language = "pl",
                            PhrasalVerbId = new Guid("00000000-0000-0000-0000-000000000011"),
                            Verb = "Odpowiadać za"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000012"),
                            Language = "pl",
                            PhrasalVerbId = new Guid("00000000-0000-0000-0000-000000000012"),
                            Verb = "Przekonać kogoś do zmiany zdania"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000013"),
                            Language = "pl",
                            PhrasalVerbId = new Guid("00000000-0000-0000-0000-000000000013"),
                            Verb = "Przedyskutować coś do końca"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000014"),
                            Language = "pl",
                            PhrasalVerbId = new Guid("00000000-0000-0000-0000-000000000014"),
                            Verb = "Pytać o"
                        });
                });

            modelBuilder.Entity("PhrasalVerbs.Application.Models.Translation", b =>
                {
                    b.HasOne("PhrasalVerbs.Application.Models.PhrasalVerb", "PhrasalVerb")
                        .WithMany("Translations")
                        .HasForeignKey("PhrasalVerbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhrasalVerb");
                });

            modelBuilder.Entity("PhrasalVerbs.Application.Models.PhrasalVerb", b =>
                {
                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
