@phrasalVerbs.API_HostAddress = http://localhost:5046

GET {{phrasalVerbs.API_HostAddress}}/api/phrasalVerbs

###

GET {{phrasalVerbs.API_HostAddress}}/api/phrasalVerbs/zonk-out

###

POST {{phrasalVerbs.API_HostAddress}}/api/phrasalVerbs
Content-Type: application/json
Accept: application/json

{
    "Verb" : "Zonk out",
    "Translations" :
    [
        {   
            "Language" : "pl",
            "Verb" : "Zasypiaæ"
        }
    ]
}

###

PUT {{phrasalVerbs.API_HostAddress}}/api/phrasalVerbs/id
Content-Type: application/json
Accept: application/json

{
    "Verb" : "Zonk out",
    "Translations" :
    [
        {   
            "Language" : "pl",
            "Verb" : "Zasypiaæ"
        },
        {   
            "Language" : "pl",
            "Verb" : "Zasn¹æ"
        }
    ]
}

###


DELETE {{phrasalVerbs.API_HostAddress}}/api/phrasalVerbs/id

###