@phrasalVerbs.API_HostAddress = http://localhost:5046

### Get all
GET {{phrasalVerbs.API_HostAddress}}/api/phrasalVerbs HTTP/1.1

### Get
GET {{phrasalVerbs.API_HostAddress}}/api/phrasalVerbs/zonk-out

### Create
POST {{phrasalVerbs.API_HostAddress}}/api/phrasalVerbs
Content-Type: application/json
Accept: application/json

{
    "Verb" : "Zonk out",
    "Translations" :
    [
        {   
            "Language" : "pl", 
            "Verb" : "Zasypiaæ"
        }
    ]
}

### Update
PUT {{phrasalVerbs.API_HostAddress}}/api/phrasalVerbs/id
Content-Type: application/json
Accept: application/json

{
    "Verb" : "Zonk out",
    "Translations" :
    [
        {   
            "Language" : "pl",
            "Verb" : "Zasypiaæ"
        },
        {   
            "Language" : "pl",
            "Verb" : "Zasn¹æ"
        }
    ]
}

### Delete
DELETE {{phrasalVerbs.API_HostAddress}}/api/phrasalVerbs/id
